# SPDX-FileCopyrightText: 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Camelot"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_packages_apps_Camelot"

[[annotations]]
path = [".github/workflows/**", ".gitignore", "app/.gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2024 Gradle, Inc."
SPDX-License-Identifier = "Apache-2.0"
